### ISSUE TITLE
How to play

### ISSUE THREAD

**Issue by leana8959** [nottyl/CheckerGame#1]
Hey

I'm trying to play this checker game, yet I don't know how to control the pieces.

Also, typing any non-numerical values crashes the program.
You can use asciinema to play my terminal recording for more information on how it crashes (also I just want to showoff asciinema)
[rec.txt](https://github.com/nottyl/CheckerGame/files/10201148/rec.txt)

Have a good morning

**Comment by nottyl** [comment]
Good idea, I knew that non-numerical values crash the program but I haven't fixed it 
You can control the pieces by their coordinates on the checker board, I've uploaded an example on [README.md](https://github.com/nottyl/CheckerGame/blob/master/README.md)
(Very complicated I know. But it's for an assignment and that's the requirement, lol)

**Comment by leana8959** [comment]
It's not really working with your instructions :(

[rec.txt](https://github.com/nottyl/CheckerGame/files/10202417/tmpfsibojqg-ascii.txt)

**Comment by nottyl** [comment]
You can't move the marble at (0,0) at the first round because no moves can be made, try starting with (3,0) for an example (because it has adjacent empty cells)

**Comment by nottyl** [comment]
Update: check this out (also wanna show off asciinema)
[example.txt](https://github.com/nottyl/CheckerGame/files/10202813/tmpfsibojqg-ascii.txt)

**Comment by leana8959** [comment]
> You can't move the marble at (0,0) at the first round because no moves can be made, try starting with (3,0) for an example (because it has adjacent empty cells)  

True, turns out I don't know how to play this game.

> Update: check this out (also wanna show off asciinema) [example.txt](https://github.com/nottyl/CheckerGame/files/10202813/tmpfsibojqg-ascii.txt)  

I tried to play it but... it looks like what I posted. Are you sure you're posting the right file? 🤡

**Comment by nottyl** [comment]
Okay. I used `sscanf` to prevent the system from crashing once the user enters non-numerical values in de54255b4ee1d586260f3bf746996ec5fef0125b. Yasss
